/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ApothekeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApothekeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApothekeResponse
        //private ApothekeResponse instance;

        public ApothekeResponseTests()
        {
            // TODO uncomment below to create an instance of ApothekeResponse
            //instance = new ApothekeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApothekeResponse
        /// </summary>
        [Fact]
        public void ApothekeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApothekeResponse
            //Assert.IsType<ApothekeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Apotheken'
        /// </summary>
        [Fact]
        public void ApothekenTest()
        {
            // TODO unit test for the property 'Apotheken'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'HasNextPage'
        /// </summary>
        [Fact]
        public void HasNextPageTest()
        {
            // TODO unit test for the property 'HasNextPage'
        }
    }
}
