/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PrescriptionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrescriptionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrescriptionDto
        //private PrescriptionDto instance;

        public PrescriptionDtoTests()
        {
            // TODO uncomment below to create an instance of PrescriptionDto
            //instance = new PrescriptionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrescriptionDto
        /// </summary>
        [Fact]
        public void PrescriptionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrescriptionDto
            //Assert.IsType<PrescriptionDto>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'RezeptUuid'
        /// </summary>
        [Fact]
        public void RezeptUuidTest()
        {
            // TODO unit test for the property 'RezeptUuid'
        }

        /// <summary>
        /// Test the property 'XmlRequest'
        /// </summary>
        [Fact]
        public void XmlRequestTest()
        {
            // TODO unit test for the property 'XmlRequest'
        }

        /// <summary>
        /// Test the property 'TransferArz'
        /// </summary>
        [Fact]
        public void TransferArzTest()
        {
            // TODO unit test for the property 'TransferArz'
        }

        /// <summary>
        /// Test the property 'RzLieferId'
        /// </summary>
        [Fact]
        public void RzLieferIdTest()
        {
            // TODO unit test for the property 'RzLieferId'
        }

        /// <summary>
        /// Test the property 'Muster16Id'
        /// </summary>
        [Fact]
        public void Muster16IdTest()
        {
            // TODO unit test for the property 'Muster16Id'
        }

        /// <summary>
        /// Test the property 'TransaktionsNummer'
        /// </summary>
        [Fact]
        public void TransaktionsNummerTest()
        {
            // TODO unit test for the property 'TransaktionsNummer'
        }

        /// <summary>
        /// Test the property 'ErezeptId'
        /// </summary>
        [Fact]
        public void ErezeptIdTest()
        {
            // TODO unit test for the property 'ErezeptId'
        }

        /// <summary>
        /// Test the property 'DatenId'
        /// </summary>
        [Fact]
        public void DatenIdTest()
        {
            // TODO unit test for the property 'DatenId'
        }
    }
}
