/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PrescriptionIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrescriptionIdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrescriptionIdentifier
        //private PrescriptionIdentifier instance;

        public PrescriptionIdentifierTests()
        {
            // TODO uncomment below to create an instance of PrescriptionIdentifier
            //instance = new PrescriptionIdentifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrescriptionIdentifier
        /// </summary>
        [Fact]
        public void PrescriptionIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrescriptionIdentifier
            //Assert.IsType<PrescriptionIdentifier>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'RezeptUuid'
        /// </summary>
        [Fact]
        public void RezeptUuidTest()
        {
            // TODO unit test for the property 'RezeptUuid'
        }
    }
}
