# coding: utf-8

# flake8: noqa
"""
    ArzTi3 Prescription Mediation API

    API for ARZ prescription insurance mediation system

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from arzti_client.models.apotheke_dto import ApothekeDto
from arzti_client.models.apotheke_response import ApothekeResponse
from arzti_client.models.bulk_operation_request import BulkOperationRequest
from arzti_client.models.bulk_operation_response import BulkOperationResponse
from arzti_client.models.create_apotheke_request import CreateApothekeRequest
from arzti_client.models.prescription_dto import PrescriptionDto
from arzti_client.models.prescription_identifier import PrescriptionIdentifier
from arzti_client.models.prescription_response import PrescriptionResponse
from arzti_client.models.update_apotheke_request import UpdateApothekeRequest
