# coding: utf-8

"""
    ArzTi3 Prescription Mediation API

    API for ARZ prescription insurance mediation system

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateApothekeRequest(BaseModel):
    """
    UpdateApothekeRequest
    """ # noqa: E501
    apotheke_name: Optional[StrictStr] = Field(alias="apothekeName")
    apotheke_name_zusatz: Optional[StrictStr] = Field(default=None, alias="apothekeNameZusatz")
    apo_ik_nr: Optional[StrictInt] = Field(default=None, alias="apoIkNr")
    inhaber_vorname: Optional[StrictStr] = Field(default=None, alias="inhaberVorname")
    inhaber_nachname: Optional[StrictStr] = Field(default=None, alias="inhaberNachname")
    apo_int_nr: Optional[StrictInt] = Field(default=None, alias="apoIntNr")
    plz: Optional[StrictInt] = None
    ort: Optional[StrictStr] = None
    strasse: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    telefon: Optional[StrictStr] = None
    mobil: Optional[StrictStr] = None
    fax: Optional[StrictStr] = None
    bemerkung: Optional[StrictStr] = None
    bundesland: Optional[StrictStr] = None
    mandant_type: Optional[StrictStr] = Field(default=None, alias="mandantType")
    id_le_type: Optional[StrictInt] = Field(default=None, alias="idLeType")
    id_hauptapotheke: Optional[StrictInt] = Field(default=None, alias="idHauptapotheke")
    id_ht_anrede: Optional[StrictInt] = Field(default=None, alias="idHtAnrede")
    filialapotheke: Optional[StrictInt] = None
    gesperrt: Optional[StrictBool] = None
    sec_login: Optional[StrictInt] = Field(default=None, alias="secLogin")
    sec_login_werte: Optional[StrictStr] = Field(default=None, alias="secLoginWerte")
    sec_login_nur_apo_user: Optional[StrictBool] = Field(default=None, alias="secLoginNurApoUser")
    __properties: ClassVar[List[str]] = ["apothekeName", "apothekeNameZusatz", "apoIkNr", "inhaberVorname", "inhaberNachname", "apoIntNr", "plz", "ort", "strasse", "email", "telefon", "mobil", "fax", "bemerkung", "bundesland", "mandantType", "idLeType", "idHauptapotheke", "idHtAnrede", "filialapotheke", "gesperrt", "secLogin", "secLoginWerte", "secLoginNurApoUser"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateApothekeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if apotheke_name (nullable) is None
        # and model_fields_set contains the field
        if self.apotheke_name is None and "apotheke_name" in self.model_fields_set:
            _dict['apothekeName'] = None

        # set to None if apotheke_name_zusatz (nullable) is None
        # and model_fields_set contains the field
        if self.apotheke_name_zusatz is None and "apotheke_name_zusatz" in self.model_fields_set:
            _dict['apothekeNameZusatz'] = None

        # set to None if inhaber_vorname (nullable) is None
        # and model_fields_set contains the field
        if self.inhaber_vorname is None and "inhaber_vorname" in self.model_fields_set:
            _dict['inhaberVorname'] = None

        # set to None if inhaber_nachname (nullable) is None
        # and model_fields_set contains the field
        if self.inhaber_nachname is None and "inhaber_nachname" in self.model_fields_set:
            _dict['inhaberNachname'] = None

        # set to None if apo_int_nr (nullable) is None
        # and model_fields_set contains the field
        if self.apo_int_nr is None and "apo_int_nr" in self.model_fields_set:
            _dict['apoIntNr'] = None

        # set to None if plz (nullable) is None
        # and model_fields_set contains the field
        if self.plz is None and "plz" in self.model_fields_set:
            _dict['plz'] = None

        # set to None if ort (nullable) is None
        # and model_fields_set contains the field
        if self.ort is None and "ort" in self.model_fields_set:
            _dict['ort'] = None

        # set to None if strasse (nullable) is None
        # and model_fields_set contains the field
        if self.strasse is None and "strasse" in self.model_fields_set:
            _dict['strasse'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if telefon (nullable) is None
        # and model_fields_set contains the field
        if self.telefon is None and "telefon" in self.model_fields_set:
            _dict['telefon'] = None

        # set to None if mobil (nullable) is None
        # and model_fields_set contains the field
        if self.mobil is None and "mobil" in self.model_fields_set:
            _dict['mobil'] = None

        # set to None if fax (nullable) is None
        # and model_fields_set contains the field
        if self.fax is None and "fax" in self.model_fields_set:
            _dict['fax'] = None

        # set to None if bemerkung (nullable) is None
        # and model_fields_set contains the field
        if self.bemerkung is None and "bemerkung" in self.model_fields_set:
            _dict['bemerkung'] = None

        # set to None if bundesland (nullable) is None
        # and model_fields_set contains the field
        if self.bundesland is None and "bundesland" in self.model_fields_set:
            _dict['bundesland'] = None

        # set to None if mandant_type (nullable) is None
        # and model_fields_set contains the field
        if self.mandant_type is None and "mandant_type" in self.model_fields_set:
            _dict['mandantType'] = None

        # set to None if id_le_type (nullable) is None
        # and model_fields_set contains the field
        if self.id_le_type is None and "id_le_type" in self.model_fields_set:
            _dict['idLeType'] = None

        # set to None if id_hauptapotheke (nullable) is None
        # and model_fields_set contains the field
        if self.id_hauptapotheke is None and "id_hauptapotheke" in self.model_fields_set:
            _dict['idHauptapotheke'] = None

        # set to None if id_ht_anrede (nullable) is None
        # and model_fields_set contains the field
        if self.id_ht_anrede is None and "id_ht_anrede" in self.model_fields_set:
            _dict['idHtAnrede'] = None

        # set to None if filialapotheke (nullable) is None
        # and model_fields_set contains the field
        if self.filialapotheke is None and "filialapotheke" in self.model_fields_set:
            _dict['filialapotheke'] = None

        # set to None if gesperrt (nullable) is None
        # and model_fields_set contains the field
        if self.gesperrt is None and "gesperrt" in self.model_fields_set:
            _dict['gesperrt'] = None

        # set to None if sec_login (nullable) is None
        # and model_fields_set contains the field
        if self.sec_login is None and "sec_login" in self.model_fields_set:
            _dict['secLogin'] = None

        # set to None if sec_login_werte (nullable) is None
        # and model_fields_set contains the field
        if self.sec_login_werte is None and "sec_login_werte" in self.model_fields_set:
            _dict['secLoginWerte'] = None

        # set to None if sec_login_nur_apo_user (nullable) is None
        # and model_fields_set contains the field
        if self.sec_login_nur_apo_user is None and "sec_login_nur_apo_user" in self.model_fields_set:
            _dict['secLoginNurApoUser'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateApothekeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apothekeName": obj.get("apothekeName"),
            "apothekeNameZusatz": obj.get("apothekeNameZusatz"),
            "apoIkNr": obj.get("apoIkNr"),
            "inhaberVorname": obj.get("inhaberVorname"),
            "inhaberNachname": obj.get("inhaberNachname"),
            "apoIntNr": obj.get("apoIntNr"),
            "plz": obj.get("plz"),
            "ort": obj.get("ort"),
            "strasse": obj.get("strasse"),
            "email": obj.get("email"),
            "telefon": obj.get("telefon"),
            "mobil": obj.get("mobil"),
            "fax": obj.get("fax"),
            "bemerkung": obj.get("bemerkung"),
            "bundesland": obj.get("bundesland"),
            "mandantType": obj.get("mandantType"),
            "idLeType": obj.get("idLeType"),
            "idHauptapotheke": obj.get("idHauptapotheke"),
            "idHtAnrede": obj.get("idHtAnrede"),
            "filialapotheke": obj.get("filialapotheke"),
            "gesperrt": obj.get("gesperrt"),
            "secLogin": obj.get("secLogin"),
            "secLoginWerte": obj.get("secLoginWerte"),
            "secLoginNurApoUser": obj.get("secLoginNurApoUser")
        })
        return _obj


