<?php
/**
 * ApothekeDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApothekeDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApothekeDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ApothekeDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id_apotheke' => 'int',
        'apotheke_name' => 'string',
        'apotheke_name_zusatz' => 'string',
        'apo_ik_nr' => 'int',
        'inhaber_vorname' => 'string',
        'inhaber_nachname' => 'string',
        'apo_int_nr' => 'int',
        'plz' => 'int',
        'ort' => 'string',
        'strasse' => 'string',
        'email' => 'string',
        'telefon' => 'string',
        'mobil' => 'string',
        'fax' => 'string',
        'bemerkung' => 'string',
        'bundesland' => 'string',
        'mandant_type' => 'string',
        'id_le_type' => 'int',
        'id_hauptapotheke' => 'int',
        'id_ht_anrede' => 'int',
        'filialapotheke' => 'int',
        'gesperrt' => 'bool',
        'sec_login' => 'int',
        'sec_login_werte' => 'string',
        'sec_login_nur_apo_user' => 'bool',
        'aen_id_sec_user' => 'int',
        'aen_datum' => '\DateTime',
        'aen_zeit' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id_apotheke' => 'int32',
        'apotheke_name' => null,
        'apotheke_name_zusatz' => null,
        'apo_ik_nr' => 'int64',
        'inhaber_vorname' => null,
        'inhaber_nachname' => null,
        'apo_int_nr' => 'int32',
        'plz' => 'int32',
        'ort' => null,
        'strasse' => null,
        'email' => null,
        'telefon' => null,
        'mobil' => null,
        'fax' => null,
        'bemerkung' => null,
        'bundesland' => null,
        'mandant_type' => null,
        'id_le_type' => 'int32',
        'id_hauptapotheke' => 'int64',
        'id_ht_anrede' => 'int32',
        'filialapotheke' => 'int32',
        'gesperrt' => null,
        'sec_login' => 'int32',
        'sec_login_werte' => null,
        'sec_login_nur_apo_user' => null,
        'aen_id_sec_user' => 'int32',
        'aen_datum' => 'date',
        'aen_zeit' => 'time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id_apotheke' => false,
        'apotheke_name' => true,
        'apotheke_name_zusatz' => true,
        'apo_ik_nr' => false,
        'inhaber_vorname' => true,
        'inhaber_nachname' => true,
        'apo_int_nr' => true,
        'plz' => true,
        'ort' => true,
        'strasse' => true,
        'email' => true,
        'telefon' => true,
        'mobil' => true,
        'fax' => true,
        'bemerkung' => true,
        'bundesland' => true,
        'mandant_type' => true,
        'id_le_type' => true,
        'id_hauptapotheke' => true,
        'id_ht_anrede' => true,
        'filialapotheke' => true,
        'gesperrt' => true,
        'sec_login' => true,
        'sec_login_werte' => true,
        'sec_login_nur_apo_user' => true,
        'aen_id_sec_user' => true,
        'aen_datum' => true,
        'aen_zeit' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_apotheke' => 'idApotheke',
        'apotheke_name' => 'apothekeName',
        'apotheke_name_zusatz' => 'apothekeNameZusatz',
        'apo_ik_nr' => 'apoIkNr',
        'inhaber_vorname' => 'inhaberVorname',
        'inhaber_nachname' => 'inhaberNachname',
        'apo_int_nr' => 'apoIntNr',
        'plz' => 'plz',
        'ort' => 'ort',
        'strasse' => 'strasse',
        'email' => 'email',
        'telefon' => 'telefon',
        'mobil' => 'mobil',
        'fax' => 'fax',
        'bemerkung' => 'bemerkung',
        'bundesland' => 'bundesland',
        'mandant_type' => 'mandantType',
        'id_le_type' => 'idLeType',
        'id_hauptapotheke' => 'idHauptapotheke',
        'id_ht_anrede' => 'idHtAnrede',
        'filialapotheke' => 'filialapotheke',
        'gesperrt' => 'gesperrt',
        'sec_login' => 'secLogin',
        'sec_login_werte' => 'secLoginWerte',
        'sec_login_nur_apo_user' => 'secLoginNurApoUser',
        'aen_id_sec_user' => 'aenIdSecUser',
        'aen_datum' => 'aenDatum',
        'aen_zeit' => 'aenZeit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_apotheke' => 'setIdApotheke',
        'apotheke_name' => 'setApothekeName',
        'apotheke_name_zusatz' => 'setApothekeNameZusatz',
        'apo_ik_nr' => 'setApoIkNr',
        'inhaber_vorname' => 'setInhaberVorname',
        'inhaber_nachname' => 'setInhaberNachname',
        'apo_int_nr' => 'setApoIntNr',
        'plz' => 'setPlz',
        'ort' => 'setOrt',
        'strasse' => 'setStrasse',
        'email' => 'setEmail',
        'telefon' => 'setTelefon',
        'mobil' => 'setMobil',
        'fax' => 'setFax',
        'bemerkung' => 'setBemerkung',
        'bundesland' => 'setBundesland',
        'mandant_type' => 'setMandantType',
        'id_le_type' => 'setIdLeType',
        'id_hauptapotheke' => 'setIdHauptapotheke',
        'id_ht_anrede' => 'setIdHtAnrede',
        'filialapotheke' => 'setFilialapotheke',
        'gesperrt' => 'setGesperrt',
        'sec_login' => 'setSecLogin',
        'sec_login_werte' => 'setSecLoginWerte',
        'sec_login_nur_apo_user' => 'setSecLoginNurApoUser',
        'aen_id_sec_user' => 'setAenIdSecUser',
        'aen_datum' => 'setAenDatum',
        'aen_zeit' => 'setAenZeit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_apotheke' => 'getIdApotheke',
        'apotheke_name' => 'getApothekeName',
        'apotheke_name_zusatz' => 'getApothekeNameZusatz',
        'apo_ik_nr' => 'getApoIkNr',
        'inhaber_vorname' => 'getInhaberVorname',
        'inhaber_nachname' => 'getInhaberNachname',
        'apo_int_nr' => 'getApoIntNr',
        'plz' => 'getPlz',
        'ort' => 'getOrt',
        'strasse' => 'getStrasse',
        'email' => 'getEmail',
        'telefon' => 'getTelefon',
        'mobil' => 'getMobil',
        'fax' => 'getFax',
        'bemerkung' => 'getBemerkung',
        'bundesland' => 'getBundesland',
        'mandant_type' => 'getMandantType',
        'id_le_type' => 'getIdLeType',
        'id_hauptapotheke' => 'getIdHauptapotheke',
        'id_ht_anrede' => 'getIdHtAnrede',
        'filialapotheke' => 'getFilialapotheke',
        'gesperrt' => 'getGesperrt',
        'sec_login' => 'getSecLogin',
        'sec_login_werte' => 'getSecLoginWerte',
        'sec_login_nur_apo_user' => 'getSecLoginNurApoUser',
        'aen_id_sec_user' => 'getAenIdSecUser',
        'aen_datum' => 'getAenDatum',
        'aen_zeit' => 'getAenZeit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id_apotheke', $data ?? [], null);
        $this->setIfExists('apotheke_name', $data ?? [], null);
        $this->setIfExists('apotheke_name_zusatz', $data ?? [], null);
        $this->setIfExists('apo_ik_nr', $data ?? [], null);
        $this->setIfExists('inhaber_vorname', $data ?? [], null);
        $this->setIfExists('inhaber_nachname', $data ?? [], null);
        $this->setIfExists('apo_int_nr', $data ?? [], null);
        $this->setIfExists('plz', $data ?? [], null);
        $this->setIfExists('ort', $data ?? [], null);
        $this->setIfExists('strasse', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('telefon', $data ?? [], null);
        $this->setIfExists('mobil', $data ?? [], null);
        $this->setIfExists('fax', $data ?? [], null);
        $this->setIfExists('bemerkung', $data ?? [], null);
        $this->setIfExists('bundesland', $data ?? [], null);
        $this->setIfExists('mandant_type', $data ?? [], null);
        $this->setIfExists('id_le_type', $data ?? [], null);
        $this->setIfExists('id_hauptapotheke', $data ?? [], null);
        $this->setIfExists('id_ht_anrede', $data ?? [], null);
        $this->setIfExists('filialapotheke', $data ?? [], null);
        $this->setIfExists('gesperrt', $data ?? [], null);
        $this->setIfExists('sec_login', $data ?? [], null);
        $this->setIfExists('sec_login_werte', $data ?? [], null);
        $this->setIfExists('sec_login_nur_apo_user', $data ?? [], null);
        $this->setIfExists('aen_id_sec_user', $data ?? [], null);
        $this->setIfExists('aen_datum', $data ?? [], null);
        $this->setIfExists('aen_zeit', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['apotheke_name'] === null) {
            $invalidProperties[] = "'apotheke_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_apotheke
     *
     * @return int|null
     */
    public function getIdApotheke()
    {
        return $this->container['id_apotheke'];
    }

    /**
     * Sets id_apotheke
     *
     * @param int|null $id_apotheke id_apotheke
     *
     * @return self
     */
    public function setIdApotheke($id_apotheke)
    {
        if (is_null($id_apotheke)) {
            throw new \InvalidArgumentException('non-nullable id_apotheke cannot be null');
        }
        $this->container['id_apotheke'] = $id_apotheke;

        return $this;
    }

    /**
     * Gets apotheke_name
     *
     * @return string
     */
    public function getApothekeName()
    {
        return $this->container['apotheke_name'];
    }

    /**
     * Sets apotheke_name
     *
     * @param string $apotheke_name apotheke_name
     *
     * @return self
     */
    public function setApothekeName($apotheke_name)
    {
        if (is_null($apotheke_name)) {
            array_push($this->openAPINullablesSetToNull, 'apotheke_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apotheke_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apotheke_name'] = $apotheke_name;

        return $this;
    }

    /**
     * Gets apotheke_name_zusatz
     *
     * @return string|null
     */
    public function getApothekeNameZusatz()
    {
        return $this->container['apotheke_name_zusatz'];
    }

    /**
     * Sets apotheke_name_zusatz
     *
     * @param string|null $apotheke_name_zusatz apotheke_name_zusatz
     *
     * @return self
     */
    public function setApothekeNameZusatz($apotheke_name_zusatz)
    {
        if (is_null($apotheke_name_zusatz)) {
            array_push($this->openAPINullablesSetToNull, 'apotheke_name_zusatz');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apotheke_name_zusatz', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apotheke_name_zusatz'] = $apotheke_name_zusatz;

        return $this;
    }

    /**
     * Gets apo_ik_nr
     *
     * @return int|null
     */
    public function getApoIkNr()
    {
        return $this->container['apo_ik_nr'];
    }

    /**
     * Sets apo_ik_nr
     *
     * @param int|null $apo_ik_nr apo_ik_nr
     *
     * @return self
     */
    public function setApoIkNr($apo_ik_nr)
    {
        if (is_null($apo_ik_nr)) {
            throw new \InvalidArgumentException('non-nullable apo_ik_nr cannot be null');
        }
        $this->container['apo_ik_nr'] = $apo_ik_nr;

        return $this;
    }

    /**
     * Gets inhaber_vorname
     *
     * @return string|null
     */
    public function getInhaberVorname()
    {
        return $this->container['inhaber_vorname'];
    }

    /**
     * Sets inhaber_vorname
     *
     * @param string|null $inhaber_vorname inhaber_vorname
     *
     * @return self
     */
    public function setInhaberVorname($inhaber_vorname)
    {
        if (is_null($inhaber_vorname)) {
            array_push($this->openAPINullablesSetToNull, 'inhaber_vorname');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('inhaber_vorname', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['inhaber_vorname'] = $inhaber_vorname;

        return $this;
    }

    /**
     * Gets inhaber_nachname
     *
     * @return string|null
     */
    public function getInhaberNachname()
    {
        return $this->container['inhaber_nachname'];
    }

    /**
     * Sets inhaber_nachname
     *
     * @param string|null $inhaber_nachname inhaber_nachname
     *
     * @return self
     */
    public function setInhaberNachname($inhaber_nachname)
    {
        if (is_null($inhaber_nachname)) {
            array_push($this->openAPINullablesSetToNull, 'inhaber_nachname');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('inhaber_nachname', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['inhaber_nachname'] = $inhaber_nachname;

        return $this;
    }

    /**
     * Gets apo_int_nr
     *
     * @return int|null
     */
    public function getApoIntNr()
    {
        return $this->container['apo_int_nr'];
    }

    /**
     * Sets apo_int_nr
     *
     * @param int|null $apo_int_nr apo_int_nr
     *
     * @return self
     */
    public function setApoIntNr($apo_int_nr)
    {
        if (is_null($apo_int_nr)) {
            array_push($this->openAPINullablesSetToNull, 'apo_int_nr');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apo_int_nr', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apo_int_nr'] = $apo_int_nr;

        return $this;
    }

    /**
     * Gets plz
     *
     * @return int|null
     */
    public function getPlz()
    {
        return $this->container['plz'];
    }

    /**
     * Sets plz
     *
     * @param int|null $plz plz
     *
     * @return self
     */
    public function setPlz($plz)
    {
        if (is_null($plz)) {
            array_push($this->openAPINullablesSetToNull, 'plz');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plz', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plz'] = $plz;

        return $this;
    }

    /**
     * Gets ort
     *
     * @return string|null
     */
    public function getOrt()
    {
        return $this->container['ort'];
    }

    /**
     * Sets ort
     *
     * @param string|null $ort ort
     *
     * @return self
     */
    public function setOrt($ort)
    {
        if (is_null($ort)) {
            array_push($this->openAPINullablesSetToNull, 'ort');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ort', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ort'] = $ort;

        return $this;
    }

    /**
     * Gets strasse
     *
     * @return string|null
     */
    public function getStrasse()
    {
        return $this->container['strasse'];
    }

    /**
     * Sets strasse
     *
     * @param string|null $strasse strasse
     *
     * @return self
     */
    public function setStrasse($strasse)
    {
        if (is_null($strasse)) {
            array_push($this->openAPINullablesSetToNull, 'strasse');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('strasse', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['strasse'] = $strasse;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets telefon
     *
     * @return string|null
     */
    public function getTelefon()
    {
        return $this->container['telefon'];
    }

    /**
     * Sets telefon
     *
     * @param string|null $telefon telefon
     *
     * @return self
     */
    public function setTelefon($telefon)
    {
        if (is_null($telefon)) {
            array_push($this->openAPINullablesSetToNull, 'telefon');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('telefon', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['telefon'] = $telefon;

        return $this;
    }

    /**
     * Gets mobil
     *
     * @return string|null
     */
    public function getMobil()
    {
        return $this->container['mobil'];
    }

    /**
     * Sets mobil
     *
     * @param string|null $mobil mobil
     *
     * @return self
     */
    public function setMobil($mobil)
    {
        if (is_null($mobil)) {
            array_push($this->openAPINullablesSetToNull, 'mobil');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mobil', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mobil'] = $mobil;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return string|null
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param string|null $fax fax
     *
     * @return self
     */
    public function setFax($fax)
    {
        if (is_null($fax)) {
            array_push($this->openAPINullablesSetToNull, 'fax');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fax', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets bemerkung
     *
     * @return string|null
     */
    public function getBemerkung()
    {
        return $this->container['bemerkung'];
    }

    /**
     * Sets bemerkung
     *
     * @param string|null $bemerkung bemerkung
     *
     * @return self
     */
    public function setBemerkung($bemerkung)
    {
        if (is_null($bemerkung)) {
            array_push($this->openAPINullablesSetToNull, 'bemerkung');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bemerkung', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bemerkung'] = $bemerkung;

        return $this;
    }

    /**
     * Gets bundesland
     *
     * @return string|null
     */
    public function getBundesland()
    {
        return $this->container['bundesland'];
    }

    /**
     * Sets bundesland
     *
     * @param string|null $bundesland bundesland
     *
     * @return self
     */
    public function setBundesland($bundesland)
    {
        if (is_null($bundesland)) {
            array_push($this->openAPINullablesSetToNull, 'bundesland');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bundesland', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bundesland'] = $bundesland;

        return $this;
    }

    /**
     * Gets mandant_type
     *
     * @return string|null
     */
    public function getMandantType()
    {
        return $this->container['mandant_type'];
    }

    /**
     * Sets mandant_type
     *
     * @param string|null $mandant_type mandant_type
     *
     * @return self
     */
    public function setMandantType($mandant_type)
    {
        if (is_null($mandant_type)) {
            array_push($this->openAPINullablesSetToNull, 'mandant_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mandant_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mandant_type'] = $mandant_type;

        return $this;
    }

    /**
     * Gets id_le_type
     *
     * @return int|null
     */
    public function getIdLeType()
    {
        return $this->container['id_le_type'];
    }

    /**
     * Sets id_le_type
     *
     * @param int|null $id_le_type id_le_type
     *
     * @return self
     */
    public function setIdLeType($id_le_type)
    {
        if (is_null($id_le_type)) {
            array_push($this->openAPINullablesSetToNull, 'id_le_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id_le_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id_le_type'] = $id_le_type;

        return $this;
    }

    /**
     * Gets id_hauptapotheke
     *
     * @return int|null
     */
    public function getIdHauptapotheke()
    {
        return $this->container['id_hauptapotheke'];
    }

    /**
     * Sets id_hauptapotheke
     *
     * @param int|null $id_hauptapotheke id_hauptapotheke
     *
     * @return self
     */
    public function setIdHauptapotheke($id_hauptapotheke)
    {
        if (is_null($id_hauptapotheke)) {
            array_push($this->openAPINullablesSetToNull, 'id_hauptapotheke');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id_hauptapotheke', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id_hauptapotheke'] = $id_hauptapotheke;

        return $this;
    }

    /**
     * Gets id_ht_anrede
     *
     * @return int|null
     */
    public function getIdHtAnrede()
    {
        return $this->container['id_ht_anrede'];
    }

    /**
     * Sets id_ht_anrede
     *
     * @param int|null $id_ht_anrede id_ht_anrede
     *
     * @return self
     */
    public function setIdHtAnrede($id_ht_anrede)
    {
        if (is_null($id_ht_anrede)) {
            array_push($this->openAPINullablesSetToNull, 'id_ht_anrede');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id_ht_anrede', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id_ht_anrede'] = $id_ht_anrede;

        return $this;
    }

    /**
     * Gets filialapotheke
     *
     * @return int|null
     */
    public function getFilialapotheke()
    {
        return $this->container['filialapotheke'];
    }

    /**
     * Sets filialapotheke
     *
     * @param int|null $filialapotheke filialapotheke
     *
     * @return self
     */
    public function setFilialapotheke($filialapotheke)
    {
        if (is_null($filialapotheke)) {
            array_push($this->openAPINullablesSetToNull, 'filialapotheke');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('filialapotheke', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['filialapotheke'] = $filialapotheke;

        return $this;
    }

    /**
     * Gets gesperrt
     *
     * @return bool|null
     */
    public function getGesperrt()
    {
        return $this->container['gesperrt'];
    }

    /**
     * Sets gesperrt
     *
     * @param bool|null $gesperrt gesperrt
     *
     * @return self
     */
    public function setGesperrt($gesperrt)
    {
        if (is_null($gesperrt)) {
            array_push($this->openAPINullablesSetToNull, 'gesperrt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gesperrt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['gesperrt'] = $gesperrt;

        return $this;
    }

    /**
     * Gets sec_login
     *
     * @return int|null
     */
    public function getSecLogin()
    {
        return $this->container['sec_login'];
    }

    /**
     * Sets sec_login
     *
     * @param int|null $sec_login sec_login
     *
     * @return self
     */
    public function setSecLogin($sec_login)
    {
        if (is_null($sec_login)) {
            array_push($this->openAPINullablesSetToNull, 'sec_login');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sec_login', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sec_login'] = $sec_login;

        return $this;
    }

    /**
     * Gets sec_login_werte
     *
     * @return string|null
     */
    public function getSecLoginWerte()
    {
        return $this->container['sec_login_werte'];
    }

    /**
     * Sets sec_login_werte
     *
     * @param string|null $sec_login_werte sec_login_werte
     *
     * @return self
     */
    public function setSecLoginWerte($sec_login_werte)
    {
        if (is_null($sec_login_werte)) {
            array_push($this->openAPINullablesSetToNull, 'sec_login_werte');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sec_login_werte', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sec_login_werte'] = $sec_login_werte;

        return $this;
    }

    /**
     * Gets sec_login_nur_apo_user
     *
     * @return bool|null
     */
    public function getSecLoginNurApoUser()
    {
        return $this->container['sec_login_nur_apo_user'];
    }

    /**
     * Sets sec_login_nur_apo_user
     *
     * @param bool|null $sec_login_nur_apo_user sec_login_nur_apo_user
     *
     * @return self
     */
    public function setSecLoginNurApoUser($sec_login_nur_apo_user)
    {
        if (is_null($sec_login_nur_apo_user)) {
            array_push($this->openAPINullablesSetToNull, 'sec_login_nur_apo_user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sec_login_nur_apo_user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sec_login_nur_apo_user'] = $sec_login_nur_apo_user;

        return $this;
    }

    /**
     * Gets aen_id_sec_user
     *
     * @return int|null
     */
    public function getAenIdSecUser()
    {
        return $this->container['aen_id_sec_user'];
    }

    /**
     * Sets aen_id_sec_user
     *
     * @param int|null $aen_id_sec_user aen_id_sec_user
     *
     * @return self
     */
    public function setAenIdSecUser($aen_id_sec_user)
    {
        if (is_null($aen_id_sec_user)) {
            array_push($this->openAPINullablesSetToNull, 'aen_id_sec_user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('aen_id_sec_user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['aen_id_sec_user'] = $aen_id_sec_user;

        return $this;
    }

    /**
     * Gets aen_datum
     *
     * @return \DateTime|null
     */
    public function getAenDatum()
    {
        return $this->container['aen_datum'];
    }

    /**
     * Sets aen_datum
     *
     * @param \DateTime|null $aen_datum aen_datum
     *
     * @return self
     */
    public function setAenDatum($aen_datum)
    {
        if (is_null($aen_datum)) {
            array_push($this->openAPINullablesSetToNull, 'aen_datum');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('aen_datum', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['aen_datum'] = $aen_datum;

        return $this;
    }

    /**
     * Gets aen_zeit
     *
     * @return string|null
     */
    public function getAenZeit()
    {
        return $this->container['aen_zeit'];
    }

    /**
     * Sets aen_zeit
     *
     * @param string|null $aen_zeit aen_zeit
     *
     * @return self
     */
    public function setAenZeit($aen_zeit)
    {
        if (is_null($aen_zeit)) {
            array_push($this->openAPINullablesSetToNull, 'aen_zeit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('aen_zeit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['aen_zeit'] = $aen_zeit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


