# coding: utf-8

"""
    ArzTi3 Prescription Mediation API

    API for ARZ prescription insurance mediation system

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arzti_client.models.apotheke_response import ApothekeResponse

class TestApothekeResponse(unittest.TestCase):
    """ApothekeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApothekeResponse:
        """Test ApothekeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApothekeResponse`
        """
        model = ApothekeResponse()
        if include_optional:
            return ApothekeResponse(
                apotheken = [
                    arzti_client.models.apotheke_dto.ApothekeDto(
                        id_apotheke = 56, 
                        apotheke_name = '', 
                        apotheke_name_zusatz = '', 
                        apo_ik_nr = 56, 
                        inhaber_vorname = '', 
                        inhaber_nachname = '', 
                        apo_int_nr = 56, 
                        plz = 56, 
                        ort = '', 
                        strasse = '', 
                        email = '', 
                        telefon = '', 
                        mobil = '', 
                        fax = '', 
                        bemerkung = '', 
                        bundesland = '', 
                        mandant_type = '', 
                        id_le_type = 56, 
                        id_hauptapotheke = 56, 
                        id_ht_anrede = 56, 
                        filialapotheke = 56, 
                        gesperrt = True, 
                        sec_login = 56, 
                        sec_login_werte = '', 
                        sec_login_nur_apo_user = True, 
                        aen_id_sec_user = 56, 
                        aen_datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        aen_zeit = '', )
                    ],
                total_count = 56,
                page = 56,
                page_size = 56,
                has_next_page = True
            )
        else:
            return ApothekeResponse(
                apotheken = [
                    arzti_client.models.apotheke_dto.ApothekeDto(
                        id_apotheke = 56, 
                        apotheke_name = '', 
                        apotheke_name_zusatz = '', 
                        apo_ik_nr = 56, 
                        inhaber_vorname = '', 
                        inhaber_nachname = '', 
                        apo_int_nr = 56, 
                        plz = 56, 
                        ort = '', 
                        strasse = '', 
                        email = '', 
                        telefon = '', 
                        mobil = '', 
                        fax = '', 
                        bemerkung = '', 
                        bundesland = '', 
                        mandant_type = '', 
                        id_le_type = 56, 
                        id_hauptapotheke = 56, 
                        id_ht_anrede = 56, 
                        filialapotheke = 56, 
                        gesperrt = True, 
                        sec_login = 56, 
                        sec_login_werte = '', 
                        sec_login_nur_apo_user = True, 
                        aen_id_sec_user = 56, 
                        aen_datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        aen_zeit = '', )
                    ],
        )
        """

    def testApothekeResponse(self):
        """Test ApothekeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
