# coding: utf-8

"""
    ArzTi3 Prescription Mediation API

    API for ARZ prescription insurance mediation system

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arzti_client.models.create_apotheke_request import CreateApothekeRequest

class TestCreateApothekeRequest(unittest.TestCase):
    """CreateApothekeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApothekeRequest:
        """Test CreateApothekeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApothekeRequest`
        """
        model = CreateApothekeRequest()
        if include_optional:
            return CreateApothekeRequest(
                apotheke_name = '',
                apotheke_name_zusatz = '',
                apo_ik_nr = 56,
                inhaber_vorname = '',
                inhaber_nachname = '',
                apo_int_nr = 56,
                plz = 56,
                ort = '',
                strasse = '',
                email = '',
                telefon = '',
                mobil = '',
                fax = '',
                bemerkung = '',
                bundesland = '',
                mandant_type = '',
                id_le_type = 56,
                id_hauptapotheke = 56,
                id_ht_anrede = 56,
                filialapotheke = 56,
                gesperrt = True,
                sec_login = 56,
                sec_login_werte = '',
                sec_login_nur_apo_user = True
            )
        else:
            return CreateApothekeRequest(
                apotheke_name = '',
        )
        """

    def testCreateApothekeRequest(self):
        """Test CreateApothekeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
