/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArzTiClient.Client.FileParameter;
using OpenAPIDateConverter = ArzTiClient.Client.OpenAPIDateConverter;

namespace ArzTiClient.Model
{
    /// <summary>
    /// ApothekeResponse
    /// </summary>
    [DataContract(Name = "ApothekeResponse")]
    public partial class ApothekeResponse : IEquatable<ApothekeResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApothekeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApothekeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApothekeResponse" /> class.
        /// </summary>
        /// <param name="apotheken">apotheken (required).</param>
        /// <param name="totalCount">totalCount.</param>
        /// <param name="page">page.</param>
        /// <param name="pageSize">pageSize.</param>
        /// <param name="hasNextPage">hasNextPage.</param>
        public ApothekeResponse(List<ApothekeDto> apotheken = default(List<ApothekeDto>), int totalCount = default(int), int page = default(int), int pageSize = default(int), bool hasNextPage = default(bool))
        {
            // to ensure "apotheken" is required (not null)
            if (apotheken == null)
            {
                throw new ArgumentNullException("apotheken is a required property for ApothekeResponse and cannot be null");
            }
            this.Apotheken = apotheken;
            this.TotalCount = totalCount;
            this.Page = page;
            this.PageSize = pageSize;
            this.HasNextPage = hasNextPage;
        }

        /// <summary>
        /// Gets or Sets Apotheken
        /// </summary>
        [DataMember(Name = "apotheken", IsRequired = true, EmitDefaultValue = true)]
        public List<ApothekeDto> Apotheken { get; set; }

        /// <summary>
        /// Gets or Sets TotalCount
        /// </summary>
        [DataMember(Name = "totalCount", EmitDefaultValue = false)]
        public int TotalCount { get; set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [DataMember(Name = "page", EmitDefaultValue = false)]
        public int Page { get; set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [DataMember(Name = "pageSize", EmitDefaultValue = false)]
        public int PageSize { get; set; }

        /// <summary>
        /// Gets or Sets HasNextPage
        /// </summary>
        [DataMember(Name = "hasNextPage", EmitDefaultValue = true)]
        public bool HasNextPage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApothekeResponse {\n");
            sb.Append("  Apotheken: ").Append(Apotheken).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  HasNextPage: ").Append(HasNextPage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApothekeResponse);
        }

        /// <summary>
        /// Returns true if ApothekeResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApothekeResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApothekeResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Apotheken == input.Apotheken ||
                    this.Apotheken != null &&
                    input.Apotheken != null &&
                    this.Apotheken.SequenceEqual(input.Apotheken)
                ) && 
                (
                    this.TotalCount == input.TotalCount ||
                    this.TotalCount.Equals(input.TotalCount)
                ) && 
                (
                    this.Page == input.Page ||
                    this.Page.Equals(input.Page)
                ) && 
                (
                    this.PageSize == input.PageSize ||
                    this.PageSize.Equals(input.PageSize)
                ) && 
                (
                    this.HasNextPage == input.HasNextPage ||
                    this.HasNextPage.Equals(input.HasNextPage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Apotheken != null)
                {
                    hashCode = (hashCode * 59) + this.Apotheken.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TotalCount.GetHashCode();
                hashCode = (hashCode * 59) + this.Page.GetHashCode();
                hashCode = (hashCode * 59) + this.PageSize.GetHashCode();
                hashCode = (hashCode * 59) + this.HasNextPage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
