/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArzTiClient.Client.FileParameter;
using OpenAPIDateConverter = ArzTiClient.Client.OpenAPIDateConverter;

namespace ArzTiClient.Model
{
    /// <summary>
    /// BulkOperationRequest
    /// </summary>
    [DataContract(Name = "BulkOperationRequest")]
    public partial class BulkOperationRequest : IEquatable<BulkOperationRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkOperationRequest" /> class.
        /// </summary>
        /// <param name="prescriptions">prescriptions.</param>
        public BulkOperationRequest(List<PrescriptionIdentifier> prescriptions = default(List<PrescriptionIdentifier>))
        {
            this.Prescriptions = prescriptions;
        }

        /// <summary>
        /// Gets or Sets Prescriptions
        /// </summary>
        [DataMember(Name = "prescriptions", EmitDefaultValue = true)]
        public List<PrescriptionIdentifier> Prescriptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkOperationRequest {\n");
            sb.Append("  Prescriptions: ").Append(Prescriptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BulkOperationRequest);
        }

        /// <summary>
        /// Returns true if BulkOperationRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of BulkOperationRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BulkOperationRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Prescriptions == input.Prescriptions ||
                    this.Prescriptions != null &&
                    input.Prescriptions != null &&
                    this.Prescriptions.SequenceEqual(input.Prescriptions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Prescriptions != null)
                {
                    hashCode = (hashCode * 59) + this.Prescriptions.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
