/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArzTiClient.Client.FileParameter;
using OpenAPIDateConverter = ArzTiClient.Client.OpenAPIDateConverter;

namespace ArzTiClient.Model
{
    /// <summary>
    /// BulkOperationResponse
    /// </summary>
    [DataContract(Name = "BulkOperationResponse")]
    public partial class BulkOperationResponse : IEquatable<BulkOperationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkOperationResponse" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="processedCount">processedCount.</param>
        /// <param name="errors">errors.</param>
        public BulkOperationResponse(bool success = default(bool), int processedCount = default(int), List<string> errors = default(List<string>))
        {
            this.Success = success;
            this.ProcessedCount = processedCount;
            this.Errors = errors;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets ProcessedCount
        /// </summary>
        [DataMember(Name = "processedCount", EmitDefaultValue = false)]
        public int ProcessedCount { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = true)]
        public List<string> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkOperationResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  ProcessedCount: ").Append(ProcessedCount).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BulkOperationResponse);
        }

        /// <summary>
        /// Returns true if BulkOperationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of BulkOperationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BulkOperationResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Success == input.Success ||
                    this.Success.Equals(input.Success)
                ) && 
                (
                    this.ProcessedCount == input.ProcessedCount ||
                    this.ProcessedCount.Equals(input.ProcessedCount)
                ) && 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    input.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Success.GetHashCode();
                hashCode = (hashCode * 59) + this.ProcessedCount.GetHashCode();
                if (this.Errors != null)
                {
                    hashCode = (hashCode * 59) + this.Errors.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
