/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArzTiClient.Client.FileParameter;
using OpenAPIDateConverter = ArzTiClient.Client.OpenAPIDateConverter;

namespace ArzTiClient.Model
{
    /// <summary>
    /// CreateApothekeRequest
    /// </summary>
    [DataContract(Name = "CreateApothekeRequest")]
    public partial class CreateApothekeRequest : IEquatable<CreateApothekeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApothekeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateApothekeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApothekeRequest" /> class.
        /// </summary>
        /// <param name="apothekeName">apothekeName (required).</param>
        /// <param name="apothekeNameZusatz">apothekeNameZusatz.</param>
        /// <param name="apoIkNr">apoIkNr.</param>
        /// <param name="inhaberVorname">inhaberVorname.</param>
        /// <param name="inhaberNachname">inhaberNachname.</param>
        /// <param name="apoIntNr">apoIntNr.</param>
        /// <param name="plz">plz.</param>
        /// <param name="ort">ort.</param>
        /// <param name="strasse">strasse.</param>
        /// <param name="email">email.</param>
        /// <param name="telefon">telefon.</param>
        /// <param name="mobil">mobil.</param>
        /// <param name="fax">fax.</param>
        /// <param name="bemerkung">bemerkung.</param>
        /// <param name="bundesland">bundesland.</param>
        /// <param name="mandantType">mandantType.</param>
        /// <param name="idLeType">idLeType.</param>
        /// <param name="idHauptapotheke">idHauptapotheke.</param>
        /// <param name="idHtAnrede">idHtAnrede.</param>
        /// <param name="filialapotheke">filialapotheke.</param>
        /// <param name="gesperrt">gesperrt.</param>
        /// <param name="secLogin">secLogin.</param>
        /// <param name="secLoginWerte">secLoginWerte.</param>
        /// <param name="secLoginNurApoUser">secLoginNurApoUser.</param>
        public CreateApothekeRequest(string apothekeName = default(string), string apothekeNameZusatz = default(string), long apoIkNr = default(long), string inhaberVorname = default(string), string inhaberNachname = default(string), int? apoIntNr = default(int?), int? plz = default(int?), string ort = default(string), string strasse = default(string), string email = default(string), string telefon = default(string), string mobil = default(string), string fax = default(string), string bemerkung = default(string), string bundesland = default(string), string mandantType = default(string), int? idLeType = default(int?), long? idHauptapotheke = default(long?), int? idHtAnrede = default(int?), int? filialapotheke = default(int?), bool? gesperrt = default(bool?), int? secLogin = default(int?), string secLoginWerte = default(string), bool? secLoginNurApoUser = default(bool?))
        {
            // to ensure "apothekeName" is required (not null)
            if (apothekeName == null)
            {
                throw new ArgumentNullException("apothekeName is a required property for CreateApothekeRequest and cannot be null");
            }
            this.ApothekeName = apothekeName;
            this.ApothekeNameZusatz = apothekeNameZusatz;
            this.ApoIkNr = apoIkNr;
            this.InhaberVorname = inhaberVorname;
            this.InhaberNachname = inhaberNachname;
            this.ApoIntNr = apoIntNr;
            this.Plz = plz;
            this.Ort = ort;
            this.Strasse = strasse;
            this.Email = email;
            this.Telefon = telefon;
            this.Mobil = mobil;
            this.Fax = fax;
            this.Bemerkung = bemerkung;
            this.Bundesland = bundesland;
            this.MandantType = mandantType;
            this.IdLeType = idLeType;
            this.IdHauptapotheke = idHauptapotheke;
            this.IdHtAnrede = idHtAnrede;
            this.Filialapotheke = filialapotheke;
            this.Gesperrt = gesperrt;
            this.SecLogin = secLogin;
            this.SecLoginWerte = secLoginWerte;
            this.SecLoginNurApoUser = secLoginNurApoUser;
        }

        /// <summary>
        /// Gets or Sets ApothekeName
        /// </summary>
        [DataMember(Name = "apothekeName", IsRequired = true, EmitDefaultValue = true)]
        public string ApothekeName { get; set; }

        /// <summary>
        /// Gets or Sets ApothekeNameZusatz
        /// </summary>
        [DataMember(Name = "apothekeNameZusatz", EmitDefaultValue = true)]
        public string ApothekeNameZusatz { get; set; }

        /// <summary>
        /// Gets or Sets ApoIkNr
        /// </summary>
        [DataMember(Name = "apoIkNr", EmitDefaultValue = false)]
        public long ApoIkNr { get; set; }

        /// <summary>
        /// Gets or Sets InhaberVorname
        /// </summary>
        [DataMember(Name = "inhaberVorname", EmitDefaultValue = true)]
        public string InhaberVorname { get; set; }

        /// <summary>
        /// Gets or Sets InhaberNachname
        /// </summary>
        [DataMember(Name = "inhaberNachname", EmitDefaultValue = true)]
        public string InhaberNachname { get; set; }

        /// <summary>
        /// Gets or Sets ApoIntNr
        /// </summary>
        [DataMember(Name = "apoIntNr", EmitDefaultValue = true)]
        public int? ApoIntNr { get; set; }

        /// <summary>
        /// Gets or Sets Plz
        /// </summary>
        [DataMember(Name = "plz", EmitDefaultValue = true)]
        public int? Plz { get; set; }

        /// <summary>
        /// Gets or Sets Ort
        /// </summary>
        [DataMember(Name = "ort", EmitDefaultValue = true)]
        public string Ort { get; set; }

        /// <summary>
        /// Gets or Sets Strasse
        /// </summary>
        [DataMember(Name = "strasse", EmitDefaultValue = true)]
        public string Strasse { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Telefon
        /// </summary>
        [DataMember(Name = "telefon", EmitDefaultValue = true)]
        public string Telefon { get; set; }

        /// <summary>
        /// Gets or Sets Mobil
        /// </summary>
        [DataMember(Name = "mobil", EmitDefaultValue = true)]
        public string Mobil { get; set; }

        /// <summary>
        /// Gets or Sets Fax
        /// </summary>
        [DataMember(Name = "fax", EmitDefaultValue = true)]
        public string Fax { get; set; }

        /// <summary>
        /// Gets or Sets Bemerkung
        /// </summary>
        [DataMember(Name = "bemerkung", EmitDefaultValue = true)]
        public string Bemerkung { get; set; }

        /// <summary>
        /// Gets or Sets Bundesland
        /// </summary>
        [DataMember(Name = "bundesland", EmitDefaultValue = true)]
        public string Bundesland { get; set; }

        /// <summary>
        /// Gets or Sets MandantType
        /// </summary>
        [DataMember(Name = "mandantType", EmitDefaultValue = true)]
        public string MandantType { get; set; }

        /// <summary>
        /// Gets or Sets IdLeType
        /// </summary>
        [DataMember(Name = "idLeType", EmitDefaultValue = true)]
        public int? IdLeType { get; set; }

        /// <summary>
        /// Gets or Sets IdHauptapotheke
        /// </summary>
        [DataMember(Name = "idHauptapotheke", EmitDefaultValue = true)]
        public long? IdHauptapotheke { get; set; }

        /// <summary>
        /// Gets or Sets IdHtAnrede
        /// </summary>
        [DataMember(Name = "idHtAnrede", EmitDefaultValue = true)]
        public int? IdHtAnrede { get; set; }

        /// <summary>
        /// Gets or Sets Filialapotheke
        /// </summary>
        [DataMember(Name = "filialapotheke", EmitDefaultValue = true)]
        public int? Filialapotheke { get; set; }

        /// <summary>
        /// Gets or Sets Gesperrt
        /// </summary>
        [DataMember(Name = "gesperrt", EmitDefaultValue = true)]
        public bool? Gesperrt { get; set; }

        /// <summary>
        /// Gets or Sets SecLogin
        /// </summary>
        [DataMember(Name = "secLogin", EmitDefaultValue = true)]
        public int? SecLogin { get; set; }

        /// <summary>
        /// Gets or Sets SecLoginWerte
        /// </summary>
        [DataMember(Name = "secLoginWerte", EmitDefaultValue = true)]
        public string SecLoginWerte { get; set; }

        /// <summary>
        /// Gets or Sets SecLoginNurApoUser
        /// </summary>
        [DataMember(Name = "secLoginNurApoUser", EmitDefaultValue = true)]
        public bool? SecLoginNurApoUser { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateApothekeRequest {\n");
            sb.Append("  ApothekeName: ").Append(ApothekeName).Append("\n");
            sb.Append("  ApothekeNameZusatz: ").Append(ApothekeNameZusatz).Append("\n");
            sb.Append("  ApoIkNr: ").Append(ApoIkNr).Append("\n");
            sb.Append("  InhaberVorname: ").Append(InhaberVorname).Append("\n");
            sb.Append("  InhaberNachname: ").Append(InhaberNachname).Append("\n");
            sb.Append("  ApoIntNr: ").Append(ApoIntNr).Append("\n");
            sb.Append("  Plz: ").Append(Plz).Append("\n");
            sb.Append("  Ort: ").Append(Ort).Append("\n");
            sb.Append("  Strasse: ").Append(Strasse).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Telefon: ").Append(Telefon).Append("\n");
            sb.Append("  Mobil: ").Append(Mobil).Append("\n");
            sb.Append("  Fax: ").Append(Fax).Append("\n");
            sb.Append("  Bemerkung: ").Append(Bemerkung).Append("\n");
            sb.Append("  Bundesland: ").Append(Bundesland).Append("\n");
            sb.Append("  MandantType: ").Append(MandantType).Append("\n");
            sb.Append("  IdLeType: ").Append(IdLeType).Append("\n");
            sb.Append("  IdHauptapotheke: ").Append(IdHauptapotheke).Append("\n");
            sb.Append("  IdHtAnrede: ").Append(IdHtAnrede).Append("\n");
            sb.Append("  Filialapotheke: ").Append(Filialapotheke).Append("\n");
            sb.Append("  Gesperrt: ").Append(Gesperrt).Append("\n");
            sb.Append("  SecLogin: ").Append(SecLogin).Append("\n");
            sb.Append("  SecLoginWerte: ").Append(SecLoginWerte).Append("\n");
            sb.Append("  SecLoginNurApoUser: ").Append(SecLoginNurApoUser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateApothekeRequest);
        }

        /// <summary>
        /// Returns true if CreateApothekeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateApothekeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateApothekeRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ApothekeName == input.ApothekeName ||
                    (this.ApothekeName != null &&
                    this.ApothekeName.Equals(input.ApothekeName))
                ) && 
                (
                    this.ApothekeNameZusatz == input.ApothekeNameZusatz ||
                    (this.ApothekeNameZusatz != null &&
                    this.ApothekeNameZusatz.Equals(input.ApothekeNameZusatz))
                ) && 
                (
                    this.ApoIkNr == input.ApoIkNr ||
                    this.ApoIkNr.Equals(input.ApoIkNr)
                ) && 
                (
                    this.InhaberVorname == input.InhaberVorname ||
                    (this.InhaberVorname != null &&
                    this.InhaberVorname.Equals(input.InhaberVorname))
                ) && 
                (
                    this.InhaberNachname == input.InhaberNachname ||
                    (this.InhaberNachname != null &&
                    this.InhaberNachname.Equals(input.InhaberNachname))
                ) && 
                (
                    this.ApoIntNr == input.ApoIntNr ||
                    (this.ApoIntNr != null &&
                    this.ApoIntNr.Equals(input.ApoIntNr))
                ) && 
                (
                    this.Plz == input.Plz ||
                    (this.Plz != null &&
                    this.Plz.Equals(input.Plz))
                ) && 
                (
                    this.Ort == input.Ort ||
                    (this.Ort != null &&
                    this.Ort.Equals(input.Ort))
                ) && 
                (
                    this.Strasse == input.Strasse ||
                    (this.Strasse != null &&
                    this.Strasse.Equals(input.Strasse))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Telefon == input.Telefon ||
                    (this.Telefon != null &&
                    this.Telefon.Equals(input.Telefon))
                ) && 
                (
                    this.Mobil == input.Mobil ||
                    (this.Mobil != null &&
                    this.Mobil.Equals(input.Mobil))
                ) && 
                (
                    this.Fax == input.Fax ||
                    (this.Fax != null &&
                    this.Fax.Equals(input.Fax))
                ) && 
                (
                    this.Bemerkung == input.Bemerkung ||
                    (this.Bemerkung != null &&
                    this.Bemerkung.Equals(input.Bemerkung))
                ) && 
                (
                    this.Bundesland == input.Bundesland ||
                    (this.Bundesland != null &&
                    this.Bundesland.Equals(input.Bundesland))
                ) && 
                (
                    this.MandantType == input.MandantType ||
                    (this.MandantType != null &&
                    this.MandantType.Equals(input.MandantType))
                ) && 
                (
                    this.IdLeType == input.IdLeType ||
                    (this.IdLeType != null &&
                    this.IdLeType.Equals(input.IdLeType))
                ) && 
                (
                    this.IdHauptapotheke == input.IdHauptapotheke ||
                    (this.IdHauptapotheke != null &&
                    this.IdHauptapotheke.Equals(input.IdHauptapotheke))
                ) && 
                (
                    this.IdHtAnrede == input.IdHtAnrede ||
                    (this.IdHtAnrede != null &&
                    this.IdHtAnrede.Equals(input.IdHtAnrede))
                ) && 
                (
                    this.Filialapotheke == input.Filialapotheke ||
                    (this.Filialapotheke != null &&
                    this.Filialapotheke.Equals(input.Filialapotheke))
                ) && 
                (
                    this.Gesperrt == input.Gesperrt ||
                    (this.Gesperrt != null &&
                    this.Gesperrt.Equals(input.Gesperrt))
                ) && 
                (
                    this.SecLogin == input.SecLogin ||
                    (this.SecLogin != null &&
                    this.SecLogin.Equals(input.SecLogin))
                ) && 
                (
                    this.SecLoginWerte == input.SecLoginWerte ||
                    (this.SecLoginWerte != null &&
                    this.SecLoginWerte.Equals(input.SecLoginWerte))
                ) && 
                (
                    this.SecLoginNurApoUser == input.SecLoginNurApoUser ||
                    (this.SecLoginNurApoUser != null &&
                    this.SecLoginNurApoUser.Equals(input.SecLoginNurApoUser))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApothekeName != null)
                {
                    hashCode = (hashCode * 59) + this.ApothekeName.GetHashCode();
                }
                if (this.ApothekeNameZusatz != null)
                {
                    hashCode = (hashCode * 59) + this.ApothekeNameZusatz.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ApoIkNr.GetHashCode();
                if (this.InhaberVorname != null)
                {
                    hashCode = (hashCode * 59) + this.InhaberVorname.GetHashCode();
                }
                if (this.InhaberNachname != null)
                {
                    hashCode = (hashCode * 59) + this.InhaberNachname.GetHashCode();
                }
                if (this.ApoIntNr != null)
                {
                    hashCode = (hashCode * 59) + this.ApoIntNr.GetHashCode();
                }
                if (this.Plz != null)
                {
                    hashCode = (hashCode * 59) + this.Plz.GetHashCode();
                }
                if (this.Ort != null)
                {
                    hashCode = (hashCode * 59) + this.Ort.GetHashCode();
                }
                if (this.Strasse != null)
                {
                    hashCode = (hashCode * 59) + this.Strasse.GetHashCode();
                }
                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }
                if (this.Telefon != null)
                {
                    hashCode = (hashCode * 59) + this.Telefon.GetHashCode();
                }
                if (this.Mobil != null)
                {
                    hashCode = (hashCode * 59) + this.Mobil.GetHashCode();
                }
                if (this.Fax != null)
                {
                    hashCode = (hashCode * 59) + this.Fax.GetHashCode();
                }
                if (this.Bemerkung != null)
                {
                    hashCode = (hashCode * 59) + this.Bemerkung.GetHashCode();
                }
                if (this.Bundesland != null)
                {
                    hashCode = (hashCode * 59) + this.Bundesland.GetHashCode();
                }
                if (this.MandantType != null)
                {
                    hashCode = (hashCode * 59) + this.MandantType.GetHashCode();
                }
                if (this.IdLeType != null)
                {
                    hashCode = (hashCode * 59) + this.IdLeType.GetHashCode();
                }
                if (this.IdHauptapotheke != null)
                {
                    hashCode = (hashCode * 59) + this.IdHauptapotheke.GetHashCode();
                }
                if (this.IdHtAnrede != null)
                {
                    hashCode = (hashCode * 59) + this.IdHtAnrede.GetHashCode();
                }
                if (this.Filialapotheke != null)
                {
                    hashCode = (hashCode * 59) + this.Filialapotheke.GetHashCode();
                }
                if (this.Gesperrt != null)
                {
                    hashCode = (hashCode * 59) + this.Gesperrt.GetHashCode();
                }
                if (this.SecLogin != null)
                {
                    hashCode = (hashCode * 59) + this.SecLogin.GetHashCode();
                }
                if (this.SecLoginWerte != null)
                {
                    hashCode = (hashCode * 59) + this.SecLoginWerte.GetHashCode();
                }
                if (this.SecLoginNurApoUser != null)
                {
                    hashCode = (hashCode * 59) + this.SecLoginNurApoUser.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
