/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArzTiClient.Client.FileParameter;
using OpenAPIDateConverter = ArzTiClient.Client.OpenAPIDateConverter;

namespace ArzTiClient.Model
{
    /// <summary>
    /// PrescriptionIdentifier
    /// </summary>
    [DataContract(Name = "PrescriptionIdentifier")]
    public partial class PrescriptionIdentifier : IEquatable<PrescriptionIdentifier>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionIdentifier" /> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="rezeptUuid">rezeptUuid.</param>
        public PrescriptionIdentifier(string type = default(string), string rezeptUuid = default(string))
        {
            this.Type = type;
            this.RezeptUuid = rezeptUuid;
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets RezeptUuid
        /// </summary>
        [DataMember(Name = "rezeptUuid", EmitDefaultValue = true)]
        public string RezeptUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrescriptionIdentifier {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  RezeptUuid: ").Append(RezeptUuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PrescriptionIdentifier);
        }

        /// <summary>
        /// Returns true if PrescriptionIdentifier instances are equal
        /// </summary>
        /// <param name="input">Instance of PrescriptionIdentifier to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrescriptionIdentifier input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.RezeptUuid == input.RezeptUuid ||
                    (this.RezeptUuid != null &&
                    this.RezeptUuid.Equals(input.RezeptUuid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                if (this.RezeptUuid != null)
                {
                    hashCode = (hashCode * 59) + this.RezeptUuid.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
