/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArzTiClient.Client.FileParameter;
using OpenAPIDateConverter = ArzTiClient.Client.OpenAPIDateConverter;

namespace ArzTiClient.Model
{
    /// <summary>
    /// PrescriptionDto
    /// </summary>
    [DataContract(Name = "PrescriptionDto")]
    public partial class PrescriptionDto : IEquatable<PrescriptionDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionDto" /> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="id">id.</param>
        /// <param name="rezeptUuid">rezeptUuid.</param>
        /// <param name="xmlRequest">xmlRequest.</param>
        /// <param name="transferArz">transferArz.</param>
        /// <param name="rzLieferId">rzLieferId.</param>
        /// <param name="muster16Id">muster16Id.</param>
        /// <param name="transaktionsNummer">transaktionsNummer.</param>
        /// <param name="erezeptId">erezeptId.</param>
        /// <param name="datenId">datenId.</param>
        public PrescriptionDto(string type = default(string), int id = default(int), string rezeptUuid = default(string), string xmlRequest = default(string), bool transferArz = default(bool), string rzLieferId = default(string), long? muster16Id = default(long?), long? transaktionsNummer = default(long?), string erezeptId = default(string), int? datenId = default(int?))
        {
            this.Type = type;
            this.Id = id;
            this.RezeptUuid = rezeptUuid;
            this.XmlRequest = xmlRequest;
            this.TransferArz = transferArz;
            this.RzLieferId = rzLieferId;
            this.Muster16Id = muster16Id;
            this.TransaktionsNummer = transaktionsNummer;
            this.ErezeptId = erezeptId;
            this.DatenId = datenId;
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets RezeptUuid
        /// </summary>
        [DataMember(Name = "rezeptUuid", EmitDefaultValue = true)]
        public string RezeptUuid { get; set; }

        /// <summary>
        /// Gets or Sets XmlRequest
        /// </summary>
        [DataMember(Name = "xmlRequest", EmitDefaultValue = true)]
        public string XmlRequest { get; set; }

        /// <summary>
        /// Gets or Sets TransferArz
        /// </summary>
        [DataMember(Name = "transferArz", EmitDefaultValue = true)]
        public bool TransferArz { get; set; }

        /// <summary>
        /// Gets or Sets RzLieferId
        /// </summary>
        [DataMember(Name = "rzLieferId", EmitDefaultValue = true)]
        public string RzLieferId { get; set; }

        /// <summary>
        /// Gets or Sets Muster16Id
        /// </summary>
        [DataMember(Name = "muster16Id", EmitDefaultValue = true)]
        public long? Muster16Id { get; set; }

        /// <summary>
        /// Gets or Sets TransaktionsNummer
        /// </summary>
        [DataMember(Name = "transaktionsNummer", EmitDefaultValue = true)]
        public long? TransaktionsNummer { get; set; }

        /// <summary>
        /// Gets or Sets ErezeptId
        /// </summary>
        [DataMember(Name = "erezeptId", EmitDefaultValue = true)]
        public string ErezeptId { get; set; }

        /// <summary>
        /// Gets or Sets DatenId
        /// </summary>
        [DataMember(Name = "datenId", EmitDefaultValue = true)]
        public int? DatenId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrescriptionDto {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RezeptUuid: ").Append(RezeptUuid).Append("\n");
            sb.Append("  XmlRequest: ").Append(XmlRequest).Append("\n");
            sb.Append("  TransferArz: ").Append(TransferArz).Append("\n");
            sb.Append("  RzLieferId: ").Append(RzLieferId).Append("\n");
            sb.Append("  Muster16Id: ").Append(Muster16Id).Append("\n");
            sb.Append("  TransaktionsNummer: ").Append(TransaktionsNummer).Append("\n");
            sb.Append("  ErezeptId: ").Append(ErezeptId).Append("\n");
            sb.Append("  DatenId: ").Append(DatenId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PrescriptionDto);
        }

        /// <summary>
        /// Returns true if PrescriptionDto instances are equal
        /// </summary>
        /// <param name="input">Instance of PrescriptionDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrescriptionDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.RezeptUuid == input.RezeptUuid ||
                    (this.RezeptUuid != null &&
                    this.RezeptUuid.Equals(input.RezeptUuid))
                ) && 
                (
                    this.XmlRequest == input.XmlRequest ||
                    (this.XmlRequest != null &&
                    this.XmlRequest.Equals(input.XmlRequest))
                ) && 
                (
                    this.TransferArz == input.TransferArz ||
                    this.TransferArz.Equals(input.TransferArz)
                ) && 
                (
                    this.RzLieferId == input.RzLieferId ||
                    (this.RzLieferId != null &&
                    this.RzLieferId.Equals(input.RzLieferId))
                ) && 
                (
                    this.Muster16Id == input.Muster16Id ||
                    (this.Muster16Id != null &&
                    this.Muster16Id.Equals(input.Muster16Id))
                ) && 
                (
                    this.TransaktionsNummer == input.TransaktionsNummer ||
                    (this.TransaktionsNummer != null &&
                    this.TransaktionsNummer.Equals(input.TransaktionsNummer))
                ) && 
                (
                    this.ErezeptId == input.ErezeptId ||
                    (this.ErezeptId != null &&
                    this.ErezeptId.Equals(input.ErezeptId))
                ) && 
                (
                    this.DatenId == input.DatenId ||
                    (this.DatenId != null &&
                    this.DatenId.Equals(input.DatenId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.RezeptUuid != null)
                {
                    hashCode = (hashCode * 59) + this.RezeptUuid.GetHashCode();
                }
                if (this.XmlRequest != null)
                {
                    hashCode = (hashCode * 59) + this.XmlRequest.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TransferArz.GetHashCode();
                if (this.RzLieferId != null)
                {
                    hashCode = (hashCode * 59) + this.RzLieferId.GetHashCode();
                }
                if (this.Muster16Id != null)
                {
                    hashCode = (hashCode * 59) + this.Muster16Id.GetHashCode();
                }
                if (this.TransaktionsNummer != null)
                {
                    hashCode = (hashCode * 59) + this.TransaktionsNummer.GetHashCode();
                }
                if (this.ErezeptId != null)
                {
                    hashCode = (hashCode * 59) + this.ErezeptId.GetHashCode();
                }
                if (this.DatenId != null)
                {
                    hashCode = (hashCode * 59) + this.DatenId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
