/*
 * ArzTi3 Prescription Mediation API
 *
 * API for ARZ prescription insurance mediation system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using ArzTiClient.Client;
using ArzTiClient.Model;

namespace ArzTiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPrescriptionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>BulkOperationResponse</returns>
        BulkOperationResponse ApiPrescriptionsMarkAsReadPost(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>ApiResponse of BulkOperationResponse</returns>
        ApiResponse<BulkOperationResponse> ApiPrescriptionsMarkAsReadPostWithHttpInfo(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <returns>PrescriptionResponse</returns>
        PrescriptionResponse ApiPrescriptionsNewGet(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <returns>ApiResponse of PrescriptionResponse</returns>
        ApiResponse<PrescriptionResponse> ApiPrescriptionsNewGetWithHttpInfo(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>BulkOperationResponse</returns>
        BulkOperationResponse ApiPrescriptionsSetAbgerechnetPost(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>ApiResponse of BulkOperationResponse</returns>
        ApiResponse<BulkOperationResponse> ApiPrescriptionsSetAbgerechnetPostWithHttpInfo(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPrescriptionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BulkOperationResponse</returns>
        System.Threading.Tasks.Task<BulkOperationResponse> ApiPrescriptionsMarkAsReadPostAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BulkOperationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BulkOperationResponse>> ApiPrescriptionsMarkAsReadPostWithHttpInfoAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PrescriptionResponse</returns>
        System.Threading.Tasks.Task<PrescriptionResponse> ApiPrescriptionsNewGetAsync(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PrescriptionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PrescriptionResponse>> ApiPrescriptionsNewGetWithHttpInfoAsync(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BulkOperationResponse</returns>
        System.Threading.Tasks.Task<BulkOperationResponse> ApiPrescriptionsSetAbgerechnetPostAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BulkOperationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BulkOperationResponse>> ApiPrescriptionsSetAbgerechnetPostWithHttpInfoAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPrescriptionsApi : IPrescriptionsApiSync, IPrescriptionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PrescriptionsApi : IDisposable, IPrescriptionsApi
    {
        private ArzTiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PrescriptionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PrescriptionsApi(string basePath)
        {
            this.Configuration = ArzTiClient.Client.Configuration.MergeConfigurations(
                ArzTiClient.Client.GlobalConfiguration.Instance,
                new ArzTiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ArzTiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ArzTiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PrescriptionsApi(ArzTiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ArzTiClient.Client.Configuration.MergeConfigurations(
                ArzTiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ArzTiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ArzTiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PrescriptionsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PrescriptionsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ArzTiClient.Client.Configuration.MergeConfigurations(
                ArzTiClient.Client.GlobalConfiguration.Instance,
                new ArzTiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ArzTiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ArzTiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PrescriptionsApi(HttpClient client, ArzTiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ArzTiClient.Client.Configuration.MergeConfigurations(
                ArzTiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ArzTiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ArzTiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrescriptionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PrescriptionsApi(ArzTiClient.Client.ISynchronousClient client, ArzTiClient.Client.IAsynchronousClient asyncClient, ArzTiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ArzTiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public ArzTiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ArzTiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ArzTiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ArzTiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ArzTiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>BulkOperationResponse</returns>
        public BulkOperationResponse ApiPrescriptionsMarkAsReadPost(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest))
        {
            ArzTiClient.Client.ApiResponse<BulkOperationResponse> localVarResponse = ApiPrescriptionsMarkAsReadPostWithHttpInfo(bulkOperationRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>ApiResponse of BulkOperationResponse</returns>
        public ArzTiClient.Client.ApiResponse<BulkOperationResponse> ApiPrescriptionsMarkAsReadPostWithHttpInfo(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest))
        {
            ArzTiClient.Client.RequestOptions localVarRequestOptions = new ArzTiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArzTiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArzTiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bulkOperationRequest;

            // authentication (basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ArzTiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BulkOperationResponse>("/api/Prescriptions/mark-as-read", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrescriptionsMarkAsReadPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BulkOperationResponse</returns>
        public async System.Threading.Tasks.Task<BulkOperationResponse> ApiPrescriptionsMarkAsReadPostAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArzTiClient.Client.ApiResponse<BulkOperationResponse> localVarResponse = await ApiPrescriptionsMarkAsReadPostWithHttpInfoAsync(bulkOperationRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BulkOperationResponse)</returns>
        public async System.Threading.Tasks.Task<ArzTiClient.Client.ApiResponse<BulkOperationResponse>> ApiPrescriptionsMarkAsReadPostWithHttpInfoAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArzTiClient.Client.RequestOptions localVarRequestOptions = new ArzTiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = ArzTiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArzTiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bulkOperationRequest;

            // authentication (basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ArzTiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<BulkOperationResponse>("/api/Prescriptions/mark-as-read", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrescriptionsMarkAsReadPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <returns>PrescriptionResponse</returns>
        public PrescriptionResponse ApiPrescriptionsNewGet(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string))
        {
            ArzTiClient.Client.ApiResponse<PrescriptionResponse> localVarResponse = ApiPrescriptionsNewGetWithHttpInfo(page, pageSize, rezeptType);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <returns>ApiResponse of PrescriptionResponse</returns>
        public ArzTiClient.Client.ApiResponse<PrescriptionResponse> ApiPrescriptionsNewGetWithHttpInfo(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string))
        {
            ArzTiClient.Client.RequestOptions localVarRequestOptions = new ArzTiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArzTiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArzTiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArzTiClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArzTiClient.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (rezeptType != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArzTiClient.Client.ClientUtils.ParameterToMultiMap("", "rezeptType", rezeptType));
            }

            // authentication (basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ArzTiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PrescriptionResponse>("/api/Prescriptions/new", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrescriptionsNewGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PrescriptionResponse</returns>
        public async System.Threading.Tasks.Task<PrescriptionResponse> ApiPrescriptionsNewGetAsync(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArzTiClient.Client.ApiResponse<PrescriptionResponse> localVarResponse = await ApiPrescriptionsNewGetWithHttpInfoAsync(page, pageSize, rezeptType, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="pageSize"> (optional, default to 100)</param>
        /// <param name="rezeptType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PrescriptionResponse)</returns>
        public async System.Threading.Tasks.Task<ArzTiClient.Client.ApiResponse<PrescriptionResponse>> ApiPrescriptionsNewGetWithHttpInfoAsync(int? page = default(int?), int? pageSize = default(int?), string rezeptType = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArzTiClient.Client.RequestOptions localVarRequestOptions = new ArzTiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = ArzTiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArzTiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArzTiClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArzTiClient.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (rezeptType != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArzTiClient.Client.ClientUtils.ParameterToMultiMap("", "rezeptType", rezeptType));
            }

            // authentication (basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ArzTiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PrescriptionResponse>("/api/Prescriptions/new", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrescriptionsNewGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>BulkOperationResponse</returns>
        public BulkOperationResponse ApiPrescriptionsSetAbgerechnetPost(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest))
        {
            ArzTiClient.Client.ApiResponse<BulkOperationResponse> localVarResponse = ApiPrescriptionsSetAbgerechnetPostWithHttpInfo(bulkOperationRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <returns>ApiResponse of BulkOperationResponse</returns>
        public ArzTiClient.Client.ApiResponse<BulkOperationResponse> ApiPrescriptionsSetAbgerechnetPostWithHttpInfo(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest))
        {
            ArzTiClient.Client.RequestOptions localVarRequestOptions = new ArzTiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArzTiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArzTiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bulkOperationRequest;

            // authentication (basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ArzTiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BulkOperationResponse>("/api/Prescriptions/set-abgerechnet", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrescriptionsSetAbgerechnetPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BulkOperationResponse</returns>
        public async System.Threading.Tasks.Task<BulkOperationResponse> ApiPrescriptionsSetAbgerechnetPostAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArzTiClient.Client.ApiResponse<BulkOperationResponse> localVarResponse = await ApiPrescriptionsSetAbgerechnetPostWithHttpInfoAsync(bulkOperationRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArzTiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkOperationRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BulkOperationResponse)</returns>
        public async System.Threading.Tasks.Task<ArzTiClient.Client.ApiResponse<BulkOperationResponse>> ApiPrescriptionsSetAbgerechnetPostWithHttpInfoAsync(BulkOperationRequest bulkOperationRequest = default(BulkOperationRequest), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArzTiClient.Client.RequestOptions localVarRequestOptions = new ArzTiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = ArzTiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArzTiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bulkOperationRequest;

            // authentication (basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ArzTiClient.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<BulkOperationResponse>("/api/Prescriptions/set-abgerechnet", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPrescriptionsSetAbgerechnetPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
